### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'Zuzka2_train/input_filtered'

### ISSUE THREAD

**Issue by sarrbranka** [OndrejTexler/Few-Shot-Patch-Based-Training#10]
This is awesome work! Thanks.
I ran into this error. Maybe its a stupid question. Do you have any idea?

```
{'type': 'DatasetPatches_M', 'dir_pre': 'Zuzka2_train/input_filtered', 'dir_post': 'Zuzka2_train/output', 'dir_mask': 'Zuzka2_train/mask', 'patch_size': 32, 'device': 'cuda:0', 'dir_x1': None, 'dir_x2': None, 'dir_x3': None, 'dir_x4': None, 'dir_x5': None, 'dir_x6': None, 'dir_x7': None, 'dir_x8': None, 'dir_x9': None}
Traceback (most recent call last):
  File "train.py", line 93, in <module>
    training_dataset = dataset_type(**d)
  File "/content/Few-Shot-Patch-Based-Training/data.py", line 152, in __init__
    self.paths_pre = sorted(os.listdir(dir_pre))
FileNotFoundError: [Errno 2] No such file or directory: 'Zuzka2_train/input_filtered'
```

**Comment by OndrejTexler** [comment]
Hello!

It is quite hard to say what is the problem. I assume you run something like this
```
python train.py --config "_config/reference_P.yaml" 
		 --data_root "Zuzka2_train" 
		 --log_interval 1000 
		 --log_folder logs_reference_P
```
Is there `Zuzka2_train` present at the location you run this script from? Meaning, is `Zuzka2_train` located in the root of the repository, on the same level as `_config`, for example?

Let me know if you were able to make it work! Good luck!

**Comment by sarrbranka** [comment]
Thank you for your reply
I forgot to unzip the TEST_DATA.zip!!

What  a time to be alive!!!

**Comment by OndrejTexler** [comment]
Great, glad the fix was that easy :-)
