### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lajiji** [OndrejTexler/Few-Shot-Patch-Based-Training#14]
Hi, I used my own dataset for training, and the following error occurred.

Traceback (most recent call last):
  File "train.py", line 138, in <module>
    trainer.train(generator, discriminator, int(config['trainer']['epochs']), args.data_root, args_config, 0) #训练策略
  File "/home/lina/style/fewshot/FSPB/trainers.py", line 153, in train
    self.test_on_full_image(generator, batch_num, data_root, config_yaml_name)
  File "/home/lina/style/fewshot/FSPB/trainers.py", line 214, in test_on_full_image
    0, 0, 0, 0, 0, generator(batch['pre'])
  File "/home/lina/miniconda3/envs/fewshot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lina/style/fewshot/FSPB/models.py", line 123, in forward
    output = self.upconv1(torch.cat((output, output_1), dim=1))
RuntimeError: Sizes of tensors must match except in dimension 2. Got 401 and 402 (The offending index is 0)

**Comment by coskuturhan** [comment]
I had the same error. Any recommendations on how to fix this?
