### ISSUE TITLE
module 'tensorflow' has no attribute 'compat

### ISSUE THREAD

**Issue by vettorazi** [OndrejTexler/Few-Shot-Patch-Based-Training#5]
Hey @OndrejTexler !
Thanks for your contribution! This is amazing and the document is very well written.
I can generate the video using your pre-trained models without any issue.

Although, when I try to train it, I receive several errors.

I tried to check all my modules and my Anaconda env. But looks like everything is just like you listed on your Repo README.
Can you help me, please?

I try to run this command, in the root folder:
`train.py --config "_config/reference_P.yaml" --data_root "Zuzka2_train" --log_interval 1000 --log_folder logs_reference_P`

and this happens:

`Traceback (most recent call last):
  File "train.py", line 8, in <module>
    from logger import Logger, ModelLogger
  File "D:\SecondHD\fewShotPatch\Few-Shot-Patch-Based-Training-master\logger.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\User\.conda\envs\TestEnv\lib\site-packages\tensorflow\__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "C:\Users\User\.conda\envs\TestEnv\lib\site-packages\tensorflow_core\__init__.py", line 42, in <module>
    from tensorflow._api.v1 import compat
  File "C:\Users\User\.conda\envs\TestEnv\lib\site-packages\tensorflow_core\_api\v1\compat\__init__.py", line 23, in <module>
    from tensorflow._api.v1.compat import v1
  File "C:\Users\User\.conda\envs\TestEnv\lib\site-packages\tensorflow_core\_api\v1\compat\v1\__init__.py", line 672, in <module>
    from tensorflow_estimator.python.estimator.api._v1 import estimator
  File "C:\Users\User\.conda\envs\TestEnv\lib\site-packages\tensorflow_estimator\__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1 import estimator
  File "C:\Users\User\.conda\envs\TestEnv\lib\site-packages\tensorflow_estimator\_api\v1\estimator\__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1.estimator import experimental
  File "C:\Users\User\.conda\envs\TestEnv\lib\site-packages\tensorflow_estimator\_api\v1\estimator\experimental\__init__.py", line 10, in <module>
    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
  File "C:\Users\User\.conda\envs\TestEnv\lib\site-packages\tensorflow_estimator\python\estimator\canned\dnn.py", line 33, in <module>
    from tensorflow_estimator.python.estimator import estimator
  File "C:\Users\User\.conda\envs\TestEnv\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 53, in <module>
    from tensorflow_estimator.python.estimator import util as estimator_util
  File "C:\Users\User\.conda\envs\TestEnv\lib\site-packages\tensorflow_estimator\python\estimator\util.py", line 75, in <module>
    class _DatasetInitializerHook(tf.compat.v1.train.SessionRunHook):
AttributeError: module 'tensorflow' has no attribute 'compat'`

I don't know if this is useful. but here's my directory tree, just to be sure I'm doing  right:
`    Directory: Few-Shot-Patch-Based-Training-master

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        10/2/2020   2:08 PM                doc
d-----        10/2/2020   2:14 PM                Lynx_gen
d-----        10/2/2020   2:14 PM                Lynx_train
d-----        10/2/2020   2:14 PM                Maruska640_gen
d-----        10/2/2020   2:14 PM                Maruska640_train
d-----        10/2/2020   2:15 PM                Zuzka1_gen
d-----        10/2/2020   2:15 PM                Zuzka1_train
d-----        10/2/2020   4:12 PM                Zuzka2_gen
d-----        10/2/2020   4:21 PM                Zuzka2_train
d-----        10/2/2020   4:16 PM                _config
d-----        10/2/2020   2:15 PM                _pre-trained-models
d-----        10/2/2020   2:48 PM                __pycache__
-a----        10/2/2020   4:12 PM            698 commandwork.js
-a----        10/1/2020   3:02 PM           2077 common_utils.py
-a----        10/1/2020   3:02 PM           1240 custom_transforms.py
-a----        10/1/2020   3:02 PM          14805 data.py
-a----        10/1/2020   3:02 PM           2860 generate.py
-a----        10/1/2020   3:02 PM            972 logger.py
-a----        10/1/2020   3:02 PM          13589 models.py
-a----        10/1/2020   3:02 PM           4264 README.md
-a----        10/1/2020   3:02 PM           5761 train.py
-a----        10/1/2020   3:02 PM          12954 trainers.py`

**Comment by vettorazi** [comment]
Hey @OndrejTexler found the issue.
conda doesn't have tensorflow 1.15.3 and I was using the 1.15.0. 
I had to install the pip directly and now I'm training! Thank you! 👍
